services:
  postgres_db:
    container_name: gavhari_db
    image: postgres
    environment:
      POSTGRES_USER: gavhari
      POSTGRES_PASSWORD: gavharipass
      PGDATA: /data/postgres
      POSTGRES_DB: gavhari
    volumes:
      - /home/gabe/workstation/gavhari_db:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - gavhari_net
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

  redis:
    image: redis
    ports:
      - "6379:6379"
    command:
      ["redis-server", "--requirepass", "gavharipass", "--appendonly", "yes"]
    volumes:
      - /home/gabe/workstation/gavhari_redis:/data
    networks:
      - gavhari_net
    restart: unless-stopped

networks:
  gavhari_net:
    driver: bridge
